source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target ‘FilmSide’ do
    pod 'Kingfisher', '~> 3.0'
    pod 'IQKeyboardManagerSwift'
    pod 'HandyJSON', '~> 1.6.1'
    pod 'Moya'
    pod 'ESPullToRefresh'
    pod 'UMengAnalytics-NO-IDFA'
    pod 'UMengUShare/UI'
    pod 'UMengUShare/Social/ReducedWeChat'
    pod 'UMengUShare/Social/ReducedQQ'
    pod 'UMengUShare/Social/ReducedSina'
    pod 'LLCycleScrollView', '~> 1.4.4'
    pod 'SnapKit', '~> 4.0.0'
end
